# Generated by Django 4.2 on 2024-10-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0005_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
