# Generated by Django 4.2 on 2024-10-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0006_alter_department_dep_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
