# Generated by Django 4.2 on 2024-10-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0014_alter_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=20)),
                ('leave_days_allowed', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('max_leaves_per_month', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_paid', models.BooleanField(default=False)),
                ('auto_approval', models.BooleanField(default=False)),
            ],
        ),
    ]
