# Generated by Django 4.2 on 2024-10-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0015_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='auto_approval',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='is_paid',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
    ]
