# Generated by Django 4.2 on 2024-10-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0016_alter_leaves_auto_approval_alter_leaves_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
