# Generated by Django 4.2 on 2024-10-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0022_leaveapplication_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_admin.employee'),
        ),
    ]
