# Generated by Django 4.2 on 2024-10-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0024_alter_leaveapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='leave_days_allowed',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='max_leaves_per_month',
            field=models.IntegerField(max_length=3),
        ),
    ]
