# Generated by Django 4.2 on 2024-10-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0026_alter_leaves_leave_days_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='leave_days_allowed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='max_leaves_per_month',
            field=models.PositiveIntegerField(),
        ),
    ]
