# Generated by Django 4.2 on 2024-10-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0027_alter_leaves_leave_days_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeement_type',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='iban_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_location',
            field=models.CharField(choices=[('ksa - kingdom of saudia arabia', 'KSA - Kingdom Of Saudia Arabia'), ('dxb - dubai', 'DXB - Dubai'), ('pk - pakistan', 'Pk - Pakistan')], max_length=35, null=True),
        ),
    ]
