# Generated by Django 4.2 on 2024-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0029_employee_onsite_salary_employee_remote_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Position',
            field=models.CharField(choices=[('developer', 'Developer')], max_length=20, null=True),
        ),
    ]
