# Generated by Django 4.2 on 2024-10-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0030_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Position',
            new_name='position',
        ),
    ]
