# Generated by Django 4.2 on 2024-10-21 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0032_educationaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaldocument',
            name='file_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='educationaldocument',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
