# Generated by Django 4.2 on 2024-10-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0038_alter_salary_total_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
