# Generated by Django 4.2 on 2024-10-28 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0043_remove_employee_employeement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hierarchy',
            old_name='approval_for',
            new_name='approval_type',
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_admin.employee'),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='is_final_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='order_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_admin.projects'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='position',
            field=models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_manager',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='hierarchy',
            unique_together={('approval_type', 'project_name', 'order_number')},
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='final_approver',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='first_approver',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='second_approver',
        ),
    ]
