# Generated by Django 4.2 on 2024-10-28 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0044_rename_approval_for_hierarchy_approval_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_admin.employee'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='order_number',
            field=models.PositiveIntegerField(),
        ),
    ]
