# Generated by Django 4.2 on 2024-10-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0045_alter_hierarchy_approver_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hierarchy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='final_approver',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='first_approver',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='remarks_final_approver',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='remarks_first_approver',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='remarks_second_approver',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='second_approver',
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='position',
            field=models.CharField(choices=[('developer', 'Developer'), ('management', 'Management')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='hierarchy',
            unique_together={('approval_type', 'position', 'project_name', 'order_number')},
        ),
    ]
