# Generated by Django 4.2 on 2024-11-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0049_alter_timesheet_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_approvers', to='main_admin.employee'),
        ),
    ]
