# Generated by Django 4.2 on 2024-11-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0051_timesheet_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='location',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('weekend', 'Weekend')], max_length=50),
        ),
    ]
