# Generated by Django 4.2 on 2024-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0058_alter_projectfile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
