# Generated by Django 4.2 on 2024-11-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0060_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_type',
            field=models.TextField(default='current account'),
        ),
        migrations.AddField(
            model_name='employee',
            name='business_unit',
            field=models.CharField(default='default_value', max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_join_again',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_exit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_entry_in_country',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_exit_from_country',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.TextField(default='123'),
        ),
        migrations.AddField(
            model_name='employee',
            name='latest_entry_in_country',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='employee',
            name='linkdln',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.TextField(choices=[('single', 'Single'), ('maried ', 'Maried'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('seperated', 'Seperated')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='mol_id',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='nick_name',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(default='default_value'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personel_phone',
            field=models.CharField(default='423424', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='rate_basis',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('n/a', 'N/A')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='reason_for_exit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='routing_code',
            field=models.TextField(default='123'),
        ),
        migrations.AddField(
            model_name='employee',
            name='source_of_hire',
            field=models.TextField(default='self', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='swift_code',
            field=models.TextField(default='123'),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_expirence',
            field=models.TextField(default='default_value', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='x_twitter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(),
        ),
    ]
