# Generated by Django 4.2 on 2024-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0061_employee_account_type_employee_business_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(),
        ),
    ]
