# Generated by Django 4.2 on 2024-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0064_alter_employee_account_type_alter_employee_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='latest_exit_from_country',
            field=models.DateField(blank=True, null=True),
        ),
    ]
