# Generated by Django 4.2 on 2024-11-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0066_remove_employee_first_exit_from_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_policy', models.CharField(max_length=50)),
            ],
        ),
    ]
