# Generated by Django 4.2 on 2024-11-30 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0067_leavepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_leave_policy', to='main_admin.leavepolicy'),
        ),
    ]
