# Generated by Django 4.2 on 2024-11-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0069_employee_sap_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sap_certifications',
            field=models.TextField(),
        ),
    ]
