# Generated by Django 4.2 on 2024-11-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0072_uploaddoctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_admin.uploaddoctype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main_admin.employee')),
            ],
        ),
    ]
