# Generated by Django 4.2 on 2024-11-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0074_employee_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv_upload',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='signed_contract',
        ),
    ]
