# Generated by Django 4.2 on 2024-11-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0076_alter_employeedocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='total_expirence',
            field=models.CharField(max_length=20),
        ),
    ]
