# Generated by Django 4.2 on 2024-12-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0077_alter_employee_total_expirence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.TextField(default='none'),
        ),
    ]
