# Generated by Django 4.2 on 2024-12-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0078_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
