# Generated by Django 4.2 on 2024-12-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0080_employee_days_from_latest_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='days_from_latest_entry',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
