# Generated by Django 4.2 on 2024-12-01 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0084_alter_employee_bank_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cv_upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='cv_uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='signed_contract',
            field=models.FileField(default=django.utils.timezone.now, upload_to='signed_contracts/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('fired', 'Fired'), ('blacklisted', 'Blacklisted'), ('terminated', 'Terminated')], max_length=20),
        ),
    ]
