# Generated by Django 4.2 on 2024-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0085_employee_cv_upload_employee_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='wps_profile',
            field=models.TextField(choices=[('yes-uae', 'Yes-UAE'), ('yes-ksa', 'Yes-KSA'), ('no', 'No')], default='no', max_length=10),
        ),
    ]
