# Generated by Django 4.2 on 2024-12-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0086_employee_wps_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(default='no skill'),
        ),
    ]
