# Generated by Django 4.2 on 2024-12-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0089_employee_reporting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='timesheet_required',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=4),
        ),
    ]
