# Generated by Django 4.2 on 2024-12-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0090_employee_timesheet_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
