# Generated by Django 4.2 on 2024-12-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0091_employeedocument_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cv_upload',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='signed_contract',
            field=models.FileField(blank=True, null=True, upload_to='signed_contracts/'),
        ),
    ]
