# Generated by Django 4.2 on 2024-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0094_alter_daterange_month_alter_daterange_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daterange',
            name='month_range',
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_country',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
