# Generated by Django 4.2 on 2024-12-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0103_clientinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='customer_type',
            field=models.CharField(choices=[('business', 'Business'), ('individual', 'Individual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='enable_portal_access',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='portal_language',
            field=models.CharField(choices=[('english', 'English'), ('arabic', 'Arabic')], max_length=50),
        ),
    ]
