# Generated by Django 4.2 on 2024-12-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0106_alter_clientinformation_enable_portal_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='enable_portal_access',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')]),
        ),
    ]
