# Generated by Django 4.2 on 2024-12-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0108_alter_clientinformation_enable_portal_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(choices=[('pakistan', 'Pakistan')], max_length=100),
        ),
    ]
