# Generated by Django 4.2 on 2024-12-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0110_alter_clientinformation_country_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinformation',
            name='enable_portal_access',
        ),
        migrations.RemoveField(
            model_name='clientinformation',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='auto_approval',
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_country',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
