# Generated by Django 4.2 on 2024-12-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0113_clientinformation_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='team_email_id',
            field=models.EmailField(default='none', max_length=254),
        ),
    ]
