# Generated by Django 4.2 on 2024-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0116_leaveapplication_resource_replacement_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='resource_replacement_email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
