# Generated by Django 4.2 on 2024-12-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0117_alter_leaveapplication_resource_replacement_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='team_email_id',
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='customer_number',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
