# Generated by Django 4.2 on 2024-12-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0124_clientinformation_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='client_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
