# Generated by Django 4.2 on 2024-12-07 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0126_paymentterms_alter_clientinformation_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='client_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_manager', to='main_admin.employee'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_sponsor', to='main_admin.employee'),
        ),
        migrations.AddField(
            model_name='projects',
            name='timesheet_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_approver', to='main_admin.employee'),
        ),
    ]
