# Generated by Django 4.2 on 2024-12-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0132_clientinformation_weekend_clientinformation_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_leave_type', models.CharField(max_length=100)),
                ('client_leave_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_leaves', to='main_admin.clientinformation')),
            ],
        ),
    ]
