# Generated by Django 5.0.2 on 2024-10-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0002_rename_bank_account_details_employee_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
