# Generated by Django 5.0.2 on 2024-10-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0003_alter_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_supervisor',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
    ]
