# Generated by Django 4.2 on 2024-10-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0008_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
