# Generated by Django 4.2 on 2024-10-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0009_alter_employee_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
    ]
