# Generated by Django 4.2 on 2024-10-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0012_alter_employee_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('manager', 'Manager')], default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pakistan', max_length=255),
        ),
    ]
