# Generated by Django 4.2 on 2024-10-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0019_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='team_members',
        ),
        migrations.AddField(
            model_name='projects',
            name='team_members',
            field=models.ManyToManyField(related_name='project_team_members', to='main_admin.employee'),
        ),
    ]
