# Generated by Django 4.2 on 2024-10-18 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0021_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_admin.employee'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
