# Generated by Django 4.2 on 2024-10-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0028_employee_account_number_employee_employeement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onsite_salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='remote_salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
