# Generated by Django 4.2 on 2024-10-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0034_leaveapplication_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task_description', models.TextField()),
                ('location', models.CharField(choices=[('onsite', 'Onsite'), ('offsite', 'Offsite'), ('remote', 'Remote')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_admin.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_admin.projects')),
            ],
        ),
    ]
