# Generated by Django 4.2 on 2024-10-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0037_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='total_salary',
            field=models.IntegerField(),
        ),
    ]
