# Generated by Django 4.2 on 2024-10-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0041_leaveapplication_final_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_approvals', to='main_admin.employee'),
        ),
    ]
