# Generated by Django 4.2 on 2024-10-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0042_leaveapplication_current_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeement_type',
        ),
    ]
