# Generated by Django 4.2 on 2024-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0046_alter_hierarchy_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='timesheet_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
