# Generated by Django 4.2 on 2024-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0047_timesheet_timesheet_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='location',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('saved', 'Saved'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
