# Generated by Django 4.2 on 2024-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0048_alter_timesheet_location_alter_timesheet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
