# Generated by Django 4.2 on 2024-11-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0050_timesheet_current_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
