# Generated by Django 4.2 on 2024-11-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0052_alter_timesheet_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='location',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('holiday', 'Holiday')], max_length=50),
        ),
    ]
