# Generated by Django 4.2 on 2024-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0057_projectfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='description',
            field=models.TextField(),
        ),
    ]
