# Generated by Django 4.2 on 2024-11-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0062_alter_employee_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business_unit',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='can_join_again',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_entry_in_country',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ifsc_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='latest_entry_in_country',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mol_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nick_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personel_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate_basis',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('n/a', 'N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='routing_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='source_of_hire',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='swift_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_expirence',
            field=models.TextField(max_length=20),
        ),
    ]
