# Generated by Django 4.2 on 2024-11-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0063_alter_employee_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_type',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='routing_code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='swift_code',
            field=models.CharField(max_length=256),
        ),
    ]
