# Generated by Django 4.2 on 2024-11-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0065_employee_latest_exit_from_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_exit_from_country',
        ),
    ]
