# Generated by Django 4.2 on 2024-11-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0068_employee_leave_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sap_certifications',
            field=models.TextField(default='none'),
        ),
    ]
