# Generated by Django 4.2 on 2024-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0070_alter_employee_sap_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mol_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
