# Generated by Django 4.2 on 2024-11-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0073_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='docs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_docs_upload', to='main_admin.uploaddoctype'),
        ),
    ]
