# Generated by Django 4.2 on 2024-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0075_remove_employee_cv_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/'),
        ),
    ]
