# Generated by Django 4.2 on 2024-12-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0092_alter_employee_cv_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterange',
            name='month',
            field=models.CharField(default='noo', max_length=50),
        ),
        migrations.AddField(
            model_name='daterange',
            name='year',
            field=models.IntegerField(default=2),
        ),
    ]
