# Generated by Django 4.2 on 2024-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0093_daterange_month_daterange_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterange',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='daterange',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
