# Generated by Django 4.2 on 2024-12-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0096_alter_employee_bank_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='time_in_hrs',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
