# Generated by Django 4.2 on 2024-12-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0099_alter_employee_billing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_relation',
            field=models.CharField(max_length=256),
        ),
    ]
