# Generated by Django 4.2 on 2024-12-05 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0101_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_docs_upload', to='main_admin.uploaddoctype'),
        ),
    ]
