# Generated by Django 4.2 on 2024-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0105_alter_clientinformation_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='enable_portal_access',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default='No'),
        ),
    ]
