# Generated by Django 4.2 on 2024-12-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0114_leaveapplication_team_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='team_email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
