# Generated by Django 4.2 on 2024-12-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0115_alter_leaveapplication_team_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='resource_replacement_email_id',
            field=models.EmailField(default='none', max_length=254),
        ),
    ]
