# Generated by Django 4.2 on 2024-12-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0118_remove_leaveapplication_team_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='customer_id',
            field=models.CharField(default=12, max_length=10),
        ),
    ]
