# Generated by Django 4.2 on 2024-12-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0119_clientinformation_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='customer_id',
            field=models.CharField(max_length=10),
        ),
    ]
