# Generated by Django 4.2 on 2024-12-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0120_alter_clientinformation_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='customer_type',
            field=models.CharField(choices=[('business', 'Business'), ('individual', 'Individual')], default='business', max_length=50),
        ),
    ]
