# Generated by Django 4.2 on 2024-12-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0121_alter_clientinformation_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='customer_type',
            field=models.CharField(choices=[('Business', 'Business'), ('Individual', 'Individual')], default='business', max_length=50),
        ),
    ]
