# Generated by Django 4.2 on 2024-12-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0122_alter_clientinformation_customer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_supervisor',
        ),
    ]
