# Generated by Django 4.2 on 2024-12-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0127_projects_client_manager_projects_project_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.TextField(),
        ),
    ]
