# Generated by Django 4.2 on 2024-12-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0128_alter_projects_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('Fixed Price', 'Fixed Price'), ('Time & Material', 'Time & Material')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
