# Generated by Django 4.2 on 2024-12-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0130_alter_projects_billing_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='billing_method',
            field=models.CharField(choices=[('Time & Material', 'Time & Material'), ('Fixed Price', 'Fixed Price')], default='Fixed Price', max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='main_admin.clientinformation'),
        ),
    ]
