# Generated by Django 4.2 on 2024-12-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0135_alter_projects_billing_method_xpl_clientcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinformation',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='clientinformation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clientinformation',
            name='last_name',
        ),
    ]
