# Generated by Django 4.2 on 2024-12-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0137_alter_projects_client_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='billing_method',
            field=models.CharField(choices=[('Time & Material', 'Time & Material'), ('Fixed Price', 'Fixed Price')], default='Fixed Price', max_length=20),
        ),
        migrations.CreateModel(
            name='XPL_EmployeeBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('Hourly', 'Hourly'), ('Fixed', 'Fixed')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='main_admin.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_billings', to='main_admin.projects')),
            ],
        ),
    ]
