# Generated by Django 4.2 on 2024-12-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0138_alter_projects_billing_method_xpl_employeebilling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='billing_method',
            field=models.CharField(choices=[('Fixed Price', 'Fixed Price'), ('Time & Material', 'Time & Material')], default='Fixed Price', max_length=20),
        ),
        migrations.AlterField(
            model_name='xpl_employeebilling',
            name='billing_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed')], max_length=50),
        ),
    ]
