# Generated by Django 4.2 on 2024-12-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0139_alter_projects_billing_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='billing_method',
            field=models.CharField(choices=[('Time & Material', 'Time & Material'), ('Fixed Price', 'Fixed Price')], default='Fixed Price', max_length=20),
        ),
        migrations.AlterField(
            model_name='xpl_employeebilling',
            name='billing_type',
            field=models.CharField(choices=[('E1', 'E1'), ('E2', 'E2'), ('A1', 'A1'), ('C1', 'C1')], max_length=50),
        ),
    ]
