# Generated by Django 4.2 on 2024-12-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0140_alter_projects_billing_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
