# Generated by Django 4.2 on 2024-12-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0141_alter_timesheet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='accept_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
