# Generated by Django 4.2 on 2024-12-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0142_timesheet_accept_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='is_editable',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='supervisor_approved',
        ),
    ]
