# Generated by Django 4.2 on 2024-12-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0144_remove_xpl_employeebilling_billing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xpl_employeebilling',
            name='billing',
        ),
        migrations.AddField(
            model_name='xpl_employeebilling',
            name='billing_type',
            field=models.CharField(choices=[('E1', 'E1'), ('E2', 'E2'), ('A1', 'A1'), ('C1', 'C1')], default='none', max_length=50),
        ),
    ]
