# Generated by Django 4.2 on 2024-12-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0145_remove_xpl_employeebilling_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpl_employeebilling',
            name='billing_type',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
