# Generated by Django 4.2 on 2024-12-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0146_alter_xpl_employeebilling_billing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtype',
            name='rate',
            field=models.PositiveBigIntegerField(default=200),
        ),
    ]
