# Generated by Django 4.2 on 2024-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0149_alter_employee_leave_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='billing_method',
            field=models.CharField(choices=[('Time & Material', 'Time & Material'), ('Fixed Price', 'Fixed Price')], default='Fixed Price', max_length=20),
        ),
    ]
