# Generated by Django 4.2 on 2024-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0151_leaves_leave_approver_alter_projects_billing_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPL_EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='XPL_Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='XPL_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='billing_method',
            field=models.CharField(choices=[('Time & Material', 'Time & Material'), ('Fixed Price', 'Fixed Price')], default='Fixed Price', max_length=20),
        ),
    ]
