# Generated by Django 4.2 on 2024-12-16 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0152_xpl_employeerole_xpl_industry_xpl_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.ForeignKey(default='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_admin.xpl_employeerole'),
        ),
    ]
