# Generated by Django 4.2 on 2024-12-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0154_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='industry',
            field=models.ForeignKey(default='IT', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_admin.xpl_industry'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='billing_method',
            field=models.CharField(choices=[('Fixed Price', 'Fixed Price'), ('Time & Material', 'Time & Material')], default='Fixed Price', max_length=20),
        ),
    ]
