# Generated by Django 4.2 on 2024-12-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0155_alter_clientinformation_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_admin.projects'),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_hours_worked',
            field=models.FloatField(default=0.0),
        ),
    ]
